name: dartpedia
description: API Wrapper for the MediaWiki API. Used to gather information from any Wikipedia Page.
version: 1.0.3
author: Benjamin Whitehead <benwhitehead21@gmail.com>
homepage: https://github.com/bmwhitehead2000/dartpedia

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^2.1.3
  test: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.example.dartpedia
    pluginClass: DartpediaPlugin