name: dartpedia
description: API Wrapper for the Wikipedia API written in Dart
version: 0.0.1
author: Benjamin Whitehead

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  dio: 2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.example.dartpedia
    pluginClass: DartpediaPlugin