name: dartpedia
description: API Wrapper for the MediaWiki API. Used to gather information from any Wikipedia Page.
version: 1.6.5
homepage: https://github.com/bmwhitehead2000/dartpedia

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  dio: ^3.0.7
  test: ^1.5.0
